import type { DemoScene } from "@/lib/demo-scenes";

export const DEMO_SCENES: DemoScene[] = [
  {
    id: "road-accident",
    label: "Road Accident",
    description: "Vehicle collision on roadway with 3 people potentially affected",
    imagePath: "/demo-scenes/road-accident.svg",
    imageAlt: "Simulated road accident scene",
    analysis: {
      incidentType: "possible_road_accident",
      confidence: 0.91,
      certaintyLabel: "likely",
      summary: "Possible road accident involving two vehicles on the roadway.",
      peoplePotentiallyAffected: {
        count: 3,
        certainty: "estimated",
        label: "3 people potentially affected",
      },
      peopleCountLabel: "3 people potentially affected",
      visibleHazards: [
        "Traffic obstruction",
        "Vehicle damage",
      ],
      visibleObjects: [
        "Two passenger vehicles",
        "Debris on roadway",
        "Road markings",
      ],
      visibleElements: [
        "Multiple vehicles",
        "Stopped traffic",
        "People near vehicles",
        "Road markings",
      ],
      environmentalClues: [
        "Roadway intersection",
        "Stopped vehicles",
        "Clear daytime conditions",
      ],
      contextualClues: [
        "Vehicles at unusual angles",
        "People standing near vehicles",
        "Traffic queue visible",
      ],
      urgencyIndicators: [
        "Traffic obstruction",
        "Active roadway hazard",
      ],
      recommendedActions: [
        "Move to a safe location away from active roadway",
        "Avoid immediate traffic hazards and vehicle debris",
        "Note the incident location (Siddaganga Institute of Technology, Tumakuru)",
        "Share concise factual information with trained emergency responders",
      ],
      recommendedFirstActions: [
        "Move to a safe location away from the roadway",
        "Avoid active traffic and visible hazards",
        "Note the incident location and landmarks",
        "Share concise factual information with emergency responders",
      ],
      notificationFacts: [
        "Incident: Possible road accident involving 2 vehicles",
        "Impact: 3 people potentially affected",
        "Hazards: Traffic obstruction, vehicle damage",
        "Location: Siddaganga Institute of Technology, Tumakuru",
      ],
      limitations: [
        "AI image analysis may be incorrect.",
        "ResQLens is an emergency-assistance prototype.",
        "Does not replace trained emergency responders or official 112/911 services.",
      ],
      uncertaintyNote:
        "AI observation only. Scene details may differ from reality. Do not rely solely on this analysis.",
    },
    location: {
      lat: 13.3485,
      lng: 77.1007,
      label: "Siddaganga Institute of Technology, Tumakuru",
      source: "demo",
      city: "Tumakuru",
      state: "Karnataka",
    },
    nearbyServices: [
      {
        id: "svc-1",
        name: "Tumakuru Government Hospital",
        category: "hospital",
        distance: "2.1 km",
        address: "B H Road, Tumakuru, Karnataka 572101",
        lat: 13.3421,
        lng: 77.1023,
        phone: "+91 816 2278250",
        isTrustedProvider: true,
      },
      {
        id: "svc-2",
        name: "Tumakuru District Police",
        category: "police",
        distance: "3.4 km",
        address: "Police Station Rd, Tumakuru, Karnataka",
        lat: 13.3389,
        lng: 77.1055,
        phone: "+91 816 2272100",
        isTrustedProvider: true,
      },
      {
        id: "svc-3",
        name: "Tumakuru Fire Station",
        category: "fire",
        distance: "4.2 km",
        address: "Fire Station Road, Tumakuru, Karnataka",
        lat: 13.3356,
        lng: 77.0989,
        phone: "+91 816 2278101",
        isTrustedProvider: true,
      },
    ],
  },
  {
    id: "fire-smoke",
    label: "Fire / Smoke",
    description: "Visible smoke and flames from structure or vehicle",
    imagePath: "/demo-scenes/fire-smoke.svg",
    imageAlt: "Simulated fire and smoke scene",
    analysis: {
      incidentType: "possible_fire_smoke",
      confidence: 0.88,
      certaintyLabel: "moderate confidence",
      summary: "Possible fire or smoke incident with visible flames and rising smoke plume.",
      peoplePotentiallyAffected: {
        count: null,
        certainty: "uncertain",
        label: "People count uncertain",
      },
      peopleCountLabel: "People count uncertain",
      visibleHazards: [
        "Visible smoke/flames",
        "Thermal heat hazard",
        "Toxic smoke inhalation risk",
      ],
      visibleObjects: [
        "Smoke plume",
        "Flames",
        "Structure perimeter",
      ],
      visibleElements: [
        "Smoke plume",
        "Possible flames",
        "Building structure",
        "Surrounding area",
      ],
      environmentalClues: [
        "Dense rising smoke",
        "Thermal discoloration",
        "Bystanders evacuating perimeter",
      ],
      contextualClues: [
        "Smoke rising from structure",
        "Discoloration indicating heat",
        "Area appears to be evacuating",
      ],
      urgencyIndicators: [
        "Active visible flames",
        "Spreading smoke hazard",
      ],
      recommendedActions: [
        "Move upwind and maintain distance from the smoke immediately",
        "Never enter smoke-filled spaces or burning structures",
        "Note the exact location and visible perimeter hazards",
        "Share concise factual information with trained fire/emergency responders",
      ],
      recommendedFirstActions: [
        "Move upwind and away from the smoke immediately",
        "Avoid inhaling smoke and keep a safe distance",
        "Note the location and what appears to be burning",
        "Contact official emergency responders immediately",
      ],
      notificationFacts: [
        "Incident: Possible fire/smoke incident",
        "Impact: People count uncertain — area evacuation required",
        "Hazards: Visible smoke/flames, thermal heat, smoke inhalation risk",
        "Location: Bengaluru, Karnataka (Demo Location)",
      ],
      limitations: [
        "AI observation only. Actual fire severity and extent may differ significantly.",
        "ResQLens is an emergency-assistance prototype.",
      ],
      uncertaintyNote:
        "AI observation only. Actual fire severity and extent may differ significantly. Treat as uncertain.",
    },
    location: {
      lat: 12.9716,
      lng: 77.5946,
      label: "Bengaluru, Karnataka (Demo Location)",
      source: "demo",
      city: "Bengaluru",
      state: "Karnataka",
    },
    nearbyServices: [
      {
        id: "svc-4",
        name: "Bowring & Lady Curzon Hospital",
        category: "hospital",
        distance: "1.8 km",
        address: "Shivaji Nagar, Bengaluru, Karnataka 560001",
        lat: 12.9762,
        lng: 77.6033,
        phone: "+91 80 2559 1362",
        isTrustedProvider: true,
      },
      {
        id: "svc-5",
        name: "Shivajinagar Police Station",
        category: "police",
        distance: "0.9 km",
        address: "Cubbon Park Rd, Bengaluru, Karnataka",
        lat: 12.9784,
        lng: 77.5983,
        phone: "+91 80 2294 2521",
        isTrustedProvider: true,
      },
      {
        id: "svc-6",
        name: "Bengaluru Fire Station",
        category: "fire",
        distance: "1.2 km",
        address: "Museum Rd, Bengaluru, Karnataka 560025",
        lat: 12.974,
        lng: 77.6012,
        phone: "+91 80 2297 1500",
        isTrustedProvider: true,
      },
    ],
  },
  {
    id: "crowd-disruption",
    label: "Crowd / Incident",
    description: "Large gathering or crowd event requiring caution and perimeter safety",
    imagePath: "/demo-scenes/crowd-disruption.svg",
    imageAlt: "Simulated crowd disruption scene",
    analysis: {
      incidentType: "possible_crowd_incident",
      confidence: 0.82,
      certaintyLabel: "moderate confidence",
      summary: "Possible crowd-related incident with multiple people visible in dense gathering.",
      peoplePotentiallyAffected: {
        count: null,
        certainty: "multiple_visible",
        label: "Multiple people visible",
      },
      peopleCountLabel: "Multiple people visible",
      visibleHazards: [
        "Scene obstruction",
        "Crowd surge potential",
        "Limited egress points",
      ],
      visibleObjects: [
        "Crowd of individuals",
        "Perimeter railings",
        "Public plaza space",
      ],
      visibleElements: [
        "Large crowd",
        "Multiple individuals",
        "Possible barriers or obstacles",
      ],
      environmentalClues: [
        "High crowd density",
        "Unusual gathering pattern",
        "Restricted movement flow",
      ],
      contextualClues: [
        "Unusual gathering",
        "Crowd movement patterns",
        "Possible distress indicators",
      ],
      urgencyIndicators: [
        "Dense crowd formation",
        "Obstruction of public walkways",
      ],
      recommendedActions: [
        "Maintain safe distance at the perimeter and do not push into dense crowds",
        "Identify clear escape and exit paths",
        "Note the location and crowd flow characteristics",
        "Share factual situation summary with event security or local responders",
      ],
      recommendedFirstActions: [
        "Observe from a safe distance and avoid entering the crowd",
        "Locate the nearest unobstructed exit route",
        "Note landmarks and crowd density indicators",
        "Notify appropriate safety staff or emergency responders",
      ],
      notificationFacts: [
        "Incident: Possible crowd-related incident",
        "Impact: Multiple people visible — crowd caution advised",
        "Hazards: Scene obstruction, surge potential, limited egress",
        "Location: Chennai, Tamil Nadu (Demo Location)",
      ],
      limitations: [
        "AI observation only. Crowd intent and safety severity are uncertain.",
        "ResQLens is an emergency-assistance prototype.",
      ],
      uncertaintyNote:
        "AI observation only. Crowd intent and severity are uncertain. Scene may be benign.",
    },
    location: {
      lat: 13.0827,
      lng: 80.2707,
      label: "Chennai, Tamil Nadu (Demo Location)",
      source: "demo",
      city: "Chennai",
      state: "Tamil Nadu",
    },
    nearbyServices: [
      {
        id: "svc-7",
        name: "Government General Hospital",
        category: "hospital",
        distance: "3.2 km",
        address: "Park Town, Chennai, Tamil Nadu 600003",
        lat: 13.0765,
        lng: 80.2783,
        phone: "+91 44 2530 5000",
        isTrustedProvider: true,
      },
      {
        id: "svc-8",
        name: "Park Town Police Station",
        category: "police",
        distance: "2.1 km",
        address: "Poonamallee High Rd, Chennai, Tamil Nadu",
        lat: 13.0807,
        lng: 80.2789,
        phone: "+91 44 2345 2588",
        isTrustedProvider: true,
      },
      {
        id: "svc-9",
        name: "Chennai Fire & Rescue",
        category: "fire",
        distance: "4.5 km",
        address: "Egmore, Chennai, Tamil Nadu 600008",
        lat: 13.0773,
        lng: 80.2609,
        phone: "+91 44 2855 4999",
        isTrustedProvider: true,
      },
    ],
  },
];
